### ISSUE TITLE
Access & edit a file

### ISSUE THREAD

**Issue by Moodai21** [provable-things/ethereum-examples#65]
Hi,
I'm currently working on an Accounting prototype based on smart contracts. Therefore I built a local ethereum blockchain, which needs access to a file/ an oracle. For this issue of getting off-chain data I found oraclize as a solution, but I'm struggeling with an implementation/ coding. I need to be able to read data of a file and also to delete some entries.Can you maybe give me a bit more introduction of how to implement such a case? Do you have something like a tutorial about that?

Thanks for your help!

**Comment by gskapka** [comment]
Hi @Moodai21 - in order to make such actions callable by an oracle, you're going to need to create some form of application that does those things, and which you expose the methods of via an API that is callable externally.

That way, you can use an Provable to create queries in order to do such operations. That's the high level over-view of one way it could work. 

As for specific implementation details when it comes to the oracle itself, our gitter channle provides the best place to get support for that. You can find it __[here](https://gitter.im/provable/ethereum-api)__.
